### ISSUE TITLE
Don't know where to enter pixel size

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/napari-plugin#5]
I _know_ that I should have a txt file with pixel size when running ADS (as per [the doc](https://axondeepseg.readthedocs.io/en/latest/documentation.html#segmentation)) but I wanted to play the 'user who does not read the doc' (like most users), and I got frustrated when I got this message. For someone not used to ADS, it is a bit unclear where to enter the pixel size info. Maybe add an entry in the GUI?

![image](https://user-images.githubusercontent.com/2482071/219907803-2c7281a9-ecf7-4ba3-8f62-d839853d7aab.png)

**Comment by Stoyan-I-A** [comment]
Thank you for raising this. Sometimes I forget to add some of the small features like this one that are already present in the current FSLeyes plugin.

**Comment by Stoyan-I-A** [comment]
fixed in daa6fa1e4efc27480a0c01f9aa9741aade69cc2d
