### ISSUE TITLE
Show progress bar (or some information that process is running)

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/napari-plugin#6]
When running the inference, the 'wheel is turning' (i'm on a mac), but apart from that there is no evidence that clicking on 'Apply ADS model' executed something and that my computer is doing something.

From a UX standpoint, it would be nice to display a pop up that says 'Segmentation in progress...' or something like that.

**Comment by Stoyan-I-A** [comment]
This is a good idea. I have a rough idea on how to implement this. It will involve doing the inference in a separate thread to prevent the main GUI from being "frozen".

**Comment by Stoyan-I-A** [comment]
fixed in daa6fa1e4efc27480a0c01f9aa9741aade69cc2d
